---
driver:
  name: vagrant

provisioner:
  name: ansible_playbook
  roles_path: /Users/aritraaritra/Documents/Projects/test-kitchen-ansible/roles

platforms:
  - name: ubuntu-16.04
    driver:
      box: bento/ubuntu-16.04

verifier:
  name: inspec

suites:
  - name: default
    provisioner:
      name: ansible_playbook
      playbook: playbooks/nodejs-playbook.yml
      hosts: default
      ansible_version: latest
      require_chef_for_busser: false
    verifier:
      inspec_tests:
        - test/smoke/default