---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  product_name: chef
  product_version: 13.3.42

platforms:
  - name: ubuntu-16.04
    driver:
      box: bento/ubuntu-16.04

verifier:
  name: inspec
 
suites:
  - name: default
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:

