---
driver:
  name: vagrant

provisioner:
  name: ansible_playbook
  roles_path: roles

platforms:
  - name: centos-7
    driver:
      box: bento/centos-7
  - name: centos-6
    driver:
      box: bento/centos-6
  

verifier:
  name: inspec

suites:
  - name: nodejs
    provisioner:
      name: ansible_playbook
      playbook: playbooks/todos-playbook.yml
      hosts: nodejs
      ansible_version: latest
      require_chef_for_busser: false
    verifier:
      inspec_tests:
        - test/integration/todos
           
  - name: nexus
    provisioner:
      name: ansible_playbook
      playbook: playbooks/nexus-playbook.yml
      hosts: nexus
      ansible_version: latest
      require_chef_for_busser: false
    verifier:
      inspec_tests:
        - test/integration/nexus

  - name: android
    provisioner:
      name: ansible_playbook
      playbook: playbooks/androidbuild-playbook.yml
      hosts: android
      ansible_version: latest
      require_chef_for_busser: false
    verifier:
      inspec_tests:
        - test/integration/android

  - name: redis
    provisioner:
      name: ansible_playbook
      playbook: playbooks/redis-playbook.yml
      hosts: redis
      ansible_version: latest
      require_chef_for_busser: false
    verifier:
      inspec_tests:
        - test/integration/redis

  - name: newrelic
    provisioner:
      name: ansible_playbook
      playbook: playbooks/newrelic-playbook.yml
      hosts: newrelic
      ansible_version: latest
      require_chef_for_busser: false
    verifier:
      inspec_tests:
        - test/integration/newrelic

  - name: jenkins
    provisioner:
      name: ansible_playbook
      playbook: playbooks/jenkins-playbook.yml
      hosts: jenkins
      ansible_version: latest
      require_chef_for_busser: false
    verifier:
      inspec_tests:
        - test/integration/jenkins

  - name: webapi
    provisioner:
      name: ansible_playbook
      playbook: playbooks/web-api-playbook.yml
      hosts: webapi
      ansible_version: latest
      require_chef_for_busser: false
    verifier:
      inspec_tests:
        - test/integration/webapi