---
driver:
  name: vagrant

provisioner:
  name: ansible_playbook
  roles_path: roles

platforms:
  - name: ubuntu-16.04
    driver:
      box: bento/ubuntu-16.04
  - name: centos-7
    driver:
      box: bento/centos-7
  - name: ubuntu-14.04
    driver:
      box: bento/ubuntu-14.04
  - name: centos-6
    driver:
      box: bento/centos-6
  

verifier:
  name: inspec

suites:
  - name: default
    provisioner:
      name: ansible_playbook
      playbook: playbooks/nodejs-playbook.yml
      hosts: default
      ansible_version: latest
      require_chef_for_busser: false
    verifier:
      inspec_tests:
        - test/integration/default