---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  product_name: chef
  product_version: 13.3.42

platforms:
  - name: ubuntu-16.04
    driver:
      box: bento/ubuntu-16.04

verifier:
  name: inspec
 
suites:
  - name: default
    run_list:
      - recipe[git_cookbook::default]
    verifier:
      inspec_tests:
        - https://github.com/nathenharvey/tmp_compliance_profile
    attributes:

