---
driver:
  name: vagrant

provisioner:
  name: ansible_playbook
  ansible_verbose: true
  ansible_verbosity: 2
  require_ruby_for_busser: false
  require_chef_for_busser: true
  hosts: all

platforms:
  - name: centos-7
    driver:
      box: bento/centos-7
 
suites:
  - name: default
  - name: splunk