# frozen_string_literal: true
source 'https://supermarket.chef.io'

# frozen_string_literal: true
cookbook 'git_cookbook', path: '/Users/aritraaritra/Documents/Projects/test-kitchen-ansible/git_cookbook'

metadata
