- hosts: webapi
  
  become: yes
  become_user: root
  
  vars:
    newrelic_service_state: started
    newrelic_license_key: <--enter new relic key-->

  roles:
    - geerlingguy.git
    - geerlingguy.docker
    - geerlingguy.nodejs
    - franklinkim.newrelic

  tasks:
    - name: Install gulp
      npm: name=gulp state=present global=yes

    - name: Install Cordova
      npm: name=cordova version='6.5.0' global=yes

    - name: Install pm2
      npm: name=pm2 version='2.5.0' global=yes

    - name: Install Development tools
      yum:
        name: "@Development tools"
        state: present
  
